create table if not exists public.personal_finance_expense_categories (
id bigint generated by default as identity primary key,
user_id uuid not null,
category_name text not null,
created_at timestamptz not null default now()
);