-- BADGEIFY / PERSONAL FINANCE - LOANS & REMINDERS
-- Run this in Supabase SQL Editor.

create table if not exists public.personal_finance_loan_people (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  person_name text not null,
  phone text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.personal_finance_loans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  person_id bigint not null references public.personal_finance_loan_people(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  loan_direction text not null default 'lent' check (loan_direction in ('lent','borrowed')),
  wallet_account_id bigint references public.personal_finance_accounts(id) on delete set null,
  loan_date date not null default current_date,
  due_date date,
  purpose text,
  notes text,
  status text not null default 'open' check (status in ('open','partially_paid','paid','cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.personal_finance_loan_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  loan_id bigint not null references public.personal_finance_loans(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  wallet_account_id bigint references public.personal_finance_accounts(id) on delete set null,
  payment_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

-- ترقية آمنة للجدول الموجود: السجلات القديمة تعتبر "فلوس مسلفها" (lent) لأنها كانت تعمل بالنظام القديم بهذه الصورة.
alter table public.personal_finance_loans
  add column if not exists loan_direction text not null default 'lent';

update public.personal_finance_loans
set loan_direction = 'lent'
where loan_direction is null;

alter table public.personal_finance_loans
  drop constraint if exists personal_finance_loans_loan_direction_check;

alter table public.personal_finance_loans
  add constraint personal_finance_loans_loan_direction_check
  check (loan_direction in ('lent','borrowed'));

create index if not exists idx_pf_loan_people_user on public.personal_finance_loan_people(user_id);
create index if not exists idx_pf_loans_user_person on public.personal_finance_loans(user_id, person_id);
create index if not exists idx_pf_loans_due on public.personal_finance_loans(user_id, due_date);
create index if not exists idx_pf_loan_payments_loan on public.personal_finance_loan_payments(loan_id);

alter table public.personal_finance_loan_people enable row level security;
alter table public.personal_finance_loans enable row level security;
alter table public.personal_finance_loan_payments enable row level security;

drop policy if exists "pf loan people owner" on public.personal_finance_loan_people;
create policy "pf loan people owner" on public.personal_finance_loan_people
for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "pf loans owner" on public.personal_finance_loans;
create policy "pf loans owner" on public.personal_finance_loans
for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "pf loan payments owner" on public.personal_finance_loan_payments;
create policy "pf loan payments owner" on public.personal_finance_loan_payments
for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- People integrity: application also normalizes/validates name + phone before insert.
-- This index blocks exact duplicate pairs at database level while allowing the same name
-- with a different phone and the same phone with a different name.
create unique index if not exists uq_pf_people_name_phone
on public.personal_finance_loan_people (user_id, person_name, phone)
where phone is not null;
