-- BADGEIFY / لوحة تحكم صالح
-- Run this once in Supabase SQL Editor.

create table if not exists public.personal_finance_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_name text not null,
  account_type text not null check (account_type in ('cash','vodafone_cash','instapay','bank','other')),
  opening_balance numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists personal_finance_accounts_user_type_idx
on public.personal_finance_accounts(user_id, account_type);

create table if not exists public.personal_finance_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id bigint not null references public.personal_finance_accounts(id) on delete restrict,
  amount numeric(14,2) not null,
  transaction_type text not null check (transaction_type in ('income','expense','transfer','adjustment')),
  category text,
  description text,
  source_type text,
  source_id text,
  customer_id bigint,
  trader_id bigint,
  payment_id bigint,
  payment_method text,
  transaction_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists personal_finance_source_unique_idx
on public.personal_finance_transactions(source_type, source_id)
where source_type is not null and source_id is not null and source_type <> 'transfer';

create index if not exists personal_finance_transactions_user_date_idx
on public.personal_finance_transactions(user_id, transaction_date desc);

alter table public.personal_finance_accounts enable row level security;
alter table public.personal_finance_transactions enable row level security;

drop policy if exists "personal_finance_accounts_owner_all" on public.personal_finance_accounts;
create policy "personal_finance_accounts_owner_all"
on public.personal_finance_accounts
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "personal_finance_transactions_owner_all" on public.personal_finance_transactions;
create policy "personal_finance_transactions_owner_all"
on public.personal_finance_transactions
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- Create the three initial wallets for the current owner when you first run this:
-- Replace YOUR_USER_UUID with the authenticated owner's UUID if desired.
-- The application will also create them automatically the first time the page opens.
