-- BADGEIFY / لوحة تحكم صالح - المرحلة الثانية

create table if not exists public.personal_finance_budgets (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 month_key text not null,
 category text not null,
 budget_amount numeric(14,2) not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(user_id,month_key,category)
);

create table if not exists public.personal_finance_goals (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 goal_name text not null,
 target_amount numeric(14,2) not null default 0,
 current_amount numeric(14,2) not null default 0,
 target_date date,
 notes text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

alter table public.personal_finance_budgets enable row level security;
alter table public.personal_finance_goals enable row level security;

drop policy if exists "personal_finance_budgets_owner_all" on public.personal_finance_budgets;
create policy "personal_finance_budgets_owner_all" on public.personal_finance_budgets
for all using (user_id=auth.uid()) with check (user_id=auth.uid());

drop policy if exists "personal_finance_goals_owner_all" on public.personal_finance_goals;
create policy "personal_finance_goals_owner_all" on public.personal_finance_goals
for all using (user_id=auth.uid()) with check (user_id=auth.uid());
